name: Pipeline techmedicos-api

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  
jobs:
##############################################################
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Restore NuGet packages
        run: dotnet restore **/**/*.csproj

      - name: Build
        run: dotnet build **/**/*.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test test/**/*.csproj --no-restore --verbosity normal

##############################################################        
  publish-image-dh:
    needs: [
      build-and-test
    ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
      - name: Build and Push TechMedicos.API Image
        working-directory: src/TechMedicos/Adapter/Driver/TechMedicos.API
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -f Dockerfile -t ${{secrets.DOCKER_USERNAME}}/techmedicos-api:latest -t ${{secrets.DOCKER_USERNAME}}/techmedicos-api:$TAG . --no-cache
          docker push ${{secrets.DOCKER_USERNAME}}/techmedicos-api:$TAG
          docker push ${{secrets.DOCKER_USERNAME}}/techmedicos-api:latest      

##############################################################

  deploy-prod:   
  
    needs: publish-image-dh    
    
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'
    environment:
      name: prod
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy AWS
        env:
            TOKEN: ${{ secrets.GTH_TOKEN  }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/g12-4soat/techmedicos-iac/actions/workflows/deployments.yml/dispatches \
          -d '{"ref":"main"}'